# Kubernetes API version
apiVersion: apps/v1
# Deployment object
kind: Deployment
metadata:
  # The name of the Deployment
  name: cloud-app-db
spec:
  # Replicas for this Deployment
  replicas: 1
  selector:
    # labels the pods
    matchLabels:
      app: cloud-app-db
  template:
    metadata:
      labels:
        # The label the pods created from the pod template should have
        app: cloud-app-db
    spec:
      nodeSelector:
        "node-role.kubernetes.io/worker": ""
      containers:
        # The container name to execute pods
        - name: cloud-app-db
          # pull postgresimage from docker hub
          image: vittolibre/cloud-app-db
          ports:
            # Assign ports to expose container
            - containerPort: 5432
          envFrom:
            # Load the environment variables/PostgresSQL credentials
            - configMapRef:
                # This should be the ConfigMap name created ealier
                name: cloud-credentials

# Kind for kubernets ConfigMap
kind: ConfigMap
metadata:
  # Name your ConfigMap
  name: cloud-db-credentials
  labels:
    app: cloud-app-db
data:
  # User DB
  POSTGRES_DB: cloud
  # Db user
  POSTGRES_USER: cloudadmin
  # Db password
  POSTGRES_PASSWORD: cloud
