# Kubernetes API version
apiVersion: apps/v1
# Deployment object
kind: Deployment
metadata:
  # The name of the Deployment
  name: edge-app-db
spec:
  # Replicas for this Deployment
  replicas: 1
  selector:
    # labels the pods
    matchLabels:
      app: edge-app-db
  template:
    metadata:
      labels:
        # The label the pods created from the pod template should have
        app: edge-app-db
    spec:
      nodeSelector:
        "node-role.kubernetes.io/edge": ""
      containers:
        # The container name to execute pods
        - name: edge-app-db
          # pull postgresimage from docker hub
          image: vittolibre/edge-app-db
          ports:
            # Assign ports to expose container
            - containerPort: 5432
          envFrom:
            # Load the environment variables/PostgresSQL credentials
            - configMapRef:
                # This should be the ConfigMap name created ealier
                name: edge-db-credentials
kind: ConfigMap
metadata:
  # Name your ConfigMap
  name: edge-db-credentials
  labels:
    app: edge-app-db
data:
  # User DB
  POSTGRES_DB: edgegateway
  # Db user
  POSTGRES_USER: edgegatewayadmin
  # Db password
  POSTGRES_PASSWORD: edgegateway
