apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-gateway
  labels:
    app: edge-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-gateway
  template:
    metadata:
      labels:
        app: edge-gateway
    spec:
      hostNetwork: true
      nodeSelector:
        "node-role.kubernetes.io/edge": ""
      containers:
      - name: edge-gateway
        image: vittolibre/edge-gateway
        env:
        - name: DB_URL
          value: "jdbc:postgresql://192.168.122.213:30045/edge"
        - name: DB_USER
          value: "edgegatewayadmin"
        - name: DB_PASSWORD
          value: "edgegateway"
        imagePullPolicy: Always
